export const theLojong = [
    {
        pointNum: "One",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 1,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Two",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 2,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Two",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 3,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Two",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 4,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Two",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 5,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Two",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 6,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Two",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 7,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Two",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 8,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Two",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 9,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Two",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 10,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Three",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 11,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Three",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 12,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Three",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 13,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Three",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 14,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Three",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 15,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Three",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 16,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Four",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 17,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Four",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 18,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Five",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 19,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Five",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 20,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Five",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 21,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Five",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 22,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 23,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 24,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 25,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 26,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 27,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 28,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 29,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 30,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 31,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 32,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 33,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 34,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 35,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 36,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 37,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Six",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 38,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 39,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 40,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 41,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 42,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 43,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 44,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 45,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 46,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 47,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 48,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 49,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 50,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 51,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 52,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 53,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 54,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 55,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 56,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 57,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 58,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
    {
        pointNum: "Seven",
        pointTitle: 'Redacted. See copyright notice in README.md',
        lojongNum: 59,
        lojongTitle: 'Redacted. See copyright notice in README.md',
    },
];
